export const countryCodes = {
  ARG: { fillKey: "MLAT" },
  AUS: { fillKey: "MLAT" },
  AUT: { fillKey: "MLAT" },
  BHS: { fillKey: "MLAT" },
  BEL: { fillKey: "MLAT" },
  BLZ: { fillKey: "MLAT" },
  BRA: { fillKey: "MLAT" },
  BGR: { fillKey: "MLAT" },
  CAN: { fillKey: "MLAT" },
  CYP: { fillKey: "MLAT" },
  CZE: { fillKey: "MLAT" },
  DNK: { fillKey: "MLAT" },
  EGY: { fillKey: "MLAT" },
  EST: { fillKey: "MLAT" },
  FIN: { fillKey: "MLAT" },
  FRA: { fillKey: "MLAT" },
  DEU: { fillKey: "MLAT" },
  GRC: { fillKey: "MLAT" },
  HUN: { fillKey: "MLAT" },
  IND: { fillKey: "MLAT" },
  IRL: { fillKey: "MLAT" },
  ISR: { fillKey: "MLAT" },
  ITA: { fillKey: "MLAT" },
  JAM: { fillKey: "MLAT" },
  JPN: { fillKey: "MLAT" },
  LVA: { fillKey: "MLAT" },
  LTU: { fillKey: "MLAT" },
  LUX: { fillKey: "MLAT" },
  MYS: { fillKey: "MLAT" },
  MEX: { fillKey: "MLAT" },
  MAR: { fillKey: "MLAT" },
  NLD: { fillKey: "MLAT" },
  NGA: { fillKey: "MLAT" },
  PAN: { fillKey: "MLAT" },
  PHL: { fillKey: "MLAT" },
  POL: { fillKey: "MLAT" },
  PRT: { fillKey: "MLAT" },
  ROU: { fillKey: "MLAT" },
  RUS: { fillKey: "MLAT" },
  SVK: { fillKey: "MLAT" },
  SVN: { fillKey: "MLAT" },
  ZAF: { fillKey: "MLAT" },
  KOR: { fillKey: "MLAT" },
  ESP: { fillKey: "MLAT" },
  SWE: { fillKey: "MLAT" },
  CHE: { fillKey: "MLAT" },
  THA: { fillKey: "MLAT" },
  TTO: { fillKey: "MLAT" },
  TUR: { fillKey: "MLAT" },
  UKR: { fillKey: "MLAT" },
  GBR: { fillKey: "MLAT" },
  VEN: { fillKey: "MLAT" },
  USA: { fillKey: "USA"}
}

export const countryList = [
  'Antigua and Barbuda',
  'Argentina',
  'Australia',
  'Austria',
  'The Bahamas',
  'Barbados',
  'Belgium',
  'Belize',
  'Bermuda',
  'Brazil',
  'Bulgaria (extradition treaty includes an agreement on certain aspects of mutual legal assistance in criminal matters)',
  'Canada',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominica',
  'Egypt',
  'Estonia',
  'Finland',
  'France (including St. Martin, French Guiana, French Polynesia, Guadeloupe, and Martinique)',
  'Germany',
  'Greece',
  'Grenada',
  'Hong Kong',
  'Hungary',
  'India',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Malta',
  'Mexico',
  'Morocco',
  'The Netherlands (including Aruba, Bonaire, Curacao, Saba, St. Eustatius, and Sint Maarten)',
  'Nigeria',
  'Panama',
  'The Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Slovakia',
  'Slovenia',
  'St. Lucia',
  'St. Kitts and Nevis',
  'St. Vincent and the Grenadines',
  'South Africa',
  'South Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Trinidad and Tobago',
  'Turkey',
  'Ukraine',
  'United Kingdom (including Anguilla, British Virgin Islands, Cayman Islands, the Isle of Man, Montserrat, and Turks and Caicos)',
  'Uruguay',
  'Venezuela'];
